### ISSUE TITLE
Import "folium" could not be resolved

### ISSUE THREAD

**Issue by rhazra-003** [python-visualization/folium#1481]
**Describe the bug**

I am working on a simple map visualizing project with django. I want to use folium for it. But I am facing some import issue.

**To Reproduce**

![folium_issue](https://user-images.githubusercontent.com/56204207/123534865-dfa45d80-d73d-11eb-9d25-86593805e92d.png)

**Expected behavior**

There shouldn't be any issue like this.

**Environment: **
 - Browser [Chrome]
 - Html file for django project
 - Python version (3.8.3 64-bit)
 - folium version (0.12.1)
 - branca version (0.4.2)

**Attempts made**

I have tried using "python -m pip install folium"command. It is getting installed but not fixing the issue.

folium is maintained by volunteers. Can you help making a fix for this issue?

**Comment by Conengmo** [comment]
I don't think this is an issue with folium, it's probably something with your local setup.

**Comment by rhazra-003** [comment]
Yeah, the issue is resolved.

Thank you!

**Comment by saminute** [comment]
Try restarting your computer. Worked for me.

**Comment by pinggol-id** [comment]
Try restarting computer, did not solve my problem. 
what is the solution, please?

**Comment by rhazra-003** [comment]
Just check if folium is downloaded in your right folder as well. Then do restart the program again, it'll work.

**Comment by Rowdypmk** [comment]
How to solve this same issue

**Comment by Rowdypmk** [comment]
But I can't solve this

**Comment by hassanraheemgull00** [comment]
ya i solve it , first i restart my laptop , then i delete my virtual env and make a new environment and install (pip install folium ) , now it works .
