### ISSUE TITLE
conda-forge folium version 0.0.0

### ISSUE THREAD

**Issue by giswqs** [python-visualization/folium#1513]
The metadata of the current folium version (v0.12.0) on conda-forge shows 0.0.0, which is causing issues for some downstream packages. 
https://anaconda.org/conda-forge/folium/files

Related issue: https://github.com/python-visualization/folium/issues/1438

![image](https://user-images.githubusercontent.com/5016453/134829544-15b884ce-b030-45a7-8722-bd0fc6361e8c.png)
![image](https://user-images.githubusercontent.com/5016453/134829669-73239c69-59db-4e9a-8d49-2fea088816c0.png)

**Comment by Conengmo** [comment]
If I remember correctly this issue was addressed and fixed in v0.12.1: https://github.com/python-visualization/folium/releases/tag/v0.12.1

Seems like 0.12.1 is not available on there? @ocefpaf?

**Comment by ocefpaf** [comment]
> Seems like 0.12.1 is not available on there? @ocefpaf?

Hmmm. Maybe I did not nailed this issue down yet. I'll investigate more. If I cannot solve it I'll revert to the old version file pattern.

**Comment by ocefpaf** [comment]
The issue was fixed in #1537 but older versions in conda-forge still have it. Version 0.12.1 has the right metadata on the conda side though but,

```
> python -c "import folium; print(folium.__version__)"
unknown
```

is still broken. I'll make a new conda-forge with the post release to fix that one.

**Comment by ocefpaf** [comment]
I'm closing this one. It should be fixed with the latest releases.

**Comment by danschef** [comment]
Well, my latest build of arosics on conda-forge still failed today on all platforms due to folium 0.0.0: see [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=421099&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=1583).

conda installs:

```
    folium:                    0.12.1.post1-pyhd8ed1ab_0  conda-forge
```

but `pip check` fails:
```
+ pip check
arosics 1.7.2 has requirement folium!=0.12.0,>=0.6.0, but you have folium 0.0.0.
```

**Comment by ocefpaf** [comment]
I have no idea what `pip check` is looking for but a fresh env reports the right version:

```
conda create --name TEST folium
conda activate TEST
python -c "import folium; print(folium.__version__)"
0.12.1.post1
```

I'll investigate but I suggest you turn off `pip check` for now.

**Comment by ocefpaf** [comment]
It turns out all we needed was to add setuptools-scm, which was wrongfully removed in the previous PR :-(
See https://github.com/conda-forge/folium-feedstock/pull/29

**Comment by danschef** [comment]
Ok nice, so could you push a new release to PyPI and conda-forge?

**Comment by ocefpaf** [comment]
> Ok nice, so could you push a new release to PyPI and conda-forge?

No need. The PyPI one is working and I added the missing setuptools-scm host dep for conda-forge. All should work now.
