### ISSUE TITLE
leaflet.awesome.rotate.css fails to load

### ISSUE THREAD

**Issue by QuLogic** [python-visualization/folium#419]
If you check the web console (in Firefox), you will see that this file fails to load:
```
The stylesheet https://raw.githubusercontent.com/python-visualization/folium/master/folium/templates/leaflet.awesome.rotate.css was not loaded because its MIME type, "text/plain", is not "text/css".
```

**Comment by JamesGardiner** [comment]
@ocefpaf this was causing me issues with strict mime type checking enabled, but should be closed by #448.

**Comment by ocefpaf** [comment]
We need a new release. I believe that was fixed in latest master. (I'll
check that as soon as I get back on office.)
Em 14/06/2016 07:32, "James Gardiner" <notifications@github.com> escreveu:

**Comment by ocefpaf** [comment]
This was fixed in #448. But the rotation is no longer working. Maybe we got blacklisted ?

**Comment by QuLogic** [comment]
Still don't know why it can't use a version-specific URL? Leaflet.js and pretty much all others are linked to a specific release already.

**Comment by ocefpaf** [comment]
> Still don't know why it can't use a version-specific URL?

No one said we cannot. PRs are welcomed!
